# Here you can define all your data sets by using simple YAML syntax.

data:
  source : "",
  type : "",
  path: "",
  bucket: "",
  numerical: [],
  categorical : []

train:
  target_col: "y",
  test_size: 0.33,
  random_state: 123,
  metrics: ["accuracy"] 

